services:
  webapp:
    build:
      context: .
      dockerfile: dockerfile
    image: webapp:1.0-SNAPSHOT
    container_name: webapp_1.0-SNAPSHOT
    depends_on:
      - webapp-db
    ports:
      - 8080:8080
      - 8787:8787
      - 9990:9990
  webapp-db:
    image: postgres:12.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgresprod
      - POSTGRES_PASSWORD=postgresprod